services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/linusfri/ladugardlive:local
    ports:
      - "80:80"
    volumes:
      - .:/app
  db:
    image: mysql:latest
    restart: always
    secrets: 
      - mysql_pass
      - mysql_rootpw
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: ladugardlive
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_pass
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_rootpw
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:

secrets:
  mysql_pass:
    external: true
  mysql_rootpw:
    external: true
