services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      USERID: 1000
      GROUPID: 1000
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: ladugardlive
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: